@Host = http://localhost:8080/api/v1

### info
POST {{Host}}/info
Content-Type: application/json

### login
POST {{Host}}/login
Content-Type: application/json

{
    "username": "anxs",
    "password": "111"
}

### get wifi info
POST {{Host}}/get_wifi_info
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODg2Mzg2MDksImlzcyI6ImF1dGgwIiwidXNlcm5hbWUiOiJhbnhzIn0.CS1N5uMorVvteSFZ_CnPlPRsQLwOhdN2R6-xRfJ3V2g",
}

### set wifi ssid
POST {{Host}}/set_wifi_ssid
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODg2Mzg2MDksImlzcyI6ImF1dGgwIiwidXNlcm5hbWUiOiJhbnhzIn0.CS1N5uMorVvteSFZ_CnPlPRsQLwOhdN2R6-xRfJ3V2g",
    "ssid": "Lacewings123"
}

### set wifi password
POST {{Host}}/set_wifi_password
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODg2Mzg2MDksImlzcyI6ImF1dGgwIiwidXNlcm5hbWUiOiJhbnhzIn0.CS1N5uMorVvteSFZ_CnPlPRsQLwOhdN2R6-xRfJ3V2g",
    "password": "11111111"
}

### set wifi channel
POST {{Host}}/set_wifi_channel
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODg2Mzg2MDksImlzcyI6ImF1dGgwIiwidXNlcm5hbWUiOiJhbnhzIn0.CS1N5uMorVvteSFZ_CnPlPRsQLwOhdN2R6-xRfJ3V2g",
    "channel": 161
}
